FileVersion = 1
Projects = {CollagenTest = {Path = "CollagenTest"}, Collagen = {Path = "."}}

[Workspace]
StartupProject = "CollagenTest"

[Configs.Test.Win32]
ConfigSelections = {CollagenTest = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {CollagenTest = {Config = "Debug"}}
